### ISSUE TITLE
Reinstate support for Gradle 3.x

### ISSUE THREAD

**Issue by flozano** [spring-gradle-plugins/dependency-management-plugin#122]
Hi,

We were thinking on moving to gradle 3 due to interest in the composite builds feature, but we depend heavily on this plugin. I just saw this commit:
https://github.com/spring-gradle-plugins/dependency-management-plugin/commit/6f1c3d9686c542960977cecb6d2a337d91f11eae

so I'm wondering what are your plans with regard to adding support for gradle 3.X in the future.

**Comment by wilkinsona** [comment]
I plan to support it while also raising the minimum supported version of Gradle to Gradle. No firm date in mind yet, but it shouldn't be too long as we'd like to officially support Gradle 3 with Spring Boot 1.5.

In the meantime, you may fine that things work fine with Gradle 3. It largely works now, with the problems all being due to obscure edge cases in Groovy's byte code and Gradle's meta-programming/proxying of the plugin's classes. There's a fix in Gradle 3.1 that fixes at least one known oddity.

**Comment by flozano** [comment]
ah, thanks for the clarification! 👍

**Comment by svachmic** [comment]
So just to clarify - if I use it in my project with Gradle 3, it will *mostly* work? Or it won't even start properly? Thanks!

**Comment by wilkinsona** [comment]
That's already explained above, isn't it?

> It largely works now

**Comment by svachmic** [comment]
I'm sorry I didn't get it that way. So I wanted to ask to be sure I understand correctly.

**Comment by 3xp0n3nt** [comment]
Bom import is working fine here with Gradle 3.2. I just wish the dependencies would be transitive, but that's not a Gradle version issue...

**Comment by wilkinsona** [comment]
As far as I can tell, things now work nicely with Gradle 3.x. I'm going to call this done (for now at least…)
