### ISSUE TITLE
ClassCastException when using maps containing GStrings to configure dependencies or dependency sets

### ISSUE THREAD

**Issue by shollander** [spring-gradle-plugins/dependency-management-plugin#148]
If I use `dependencySet` with a gradle property like this:
```
dependencySet( group: 'com.something', version: "${something.version}") {
  entry 'entry-abc'
  entry 'entry-def'
}
```

I get the following error: 
```
org.codehaus.groovy.runtime.GStringImpl cannot be cast to java.lang.String
 at io.spring.gradle.dependencymanagement.internal.dsl.StandardDependenciesHandler.dependencySet (StandardDependenciesHandler.java:123)
....
```
I am using Gradle 3.3 with dependency-management-plugin 1.0.0.RELEASE

I can work around it by calling `toString()` on the property but that is a little awkward. I think dependency
dependency-management-plugin should be handling this.

**Comment by wilkinsona** [comment]
Why are you using a GString there? It doesn't appear to be necessary

**Comment by shollander** [comment]
I am not explicitly using a GString anywhere. Apparently in newer versions of Gradle, when referencing a property you get a GString instead of a String. The `${something.version}` property is a regular property defined in my `gradle.properties` file.

**Comment by wilkinsona** [comment]
`"${something.version}"` is a `GString`. Furthermore, if you've configured `something.version` in `gradle.properties`, "${something.version}" won't reference it. Instead, its value will be the value of the `version` property of whatever `something` resolves to. It'll probably fail because `something` doesn't exist. For this reason, I'd avoid using `.` character in the names of your properties.

If you name you property `somethingVersion` you can reference it like this:

```
dependencyManagement {
	dependencies {
		dependencySet(group: 'com.something', version: somethingVersion) {
			entry 'entry-abc'
			entry 'entry-def'
		}
	}
}
```

> Apparently in newer versions of Gradle, when referencing a property you get a GString instead of a String

I don't believe that's the case. The above works fine with Gradle 3.3.

None of this is to say that the plugin can't be improved here, but I want to be sure that the scope of the problem is understood first.

**Comment by shollander** [comment]
You are correct regarding the dot character. This was contrived example and I hadn't translated that part properly - my apologies. I had actually been using something similar to `somethingVersion` like you mentioned. When used as a string (`"${somethingVersion}"`) I get the GSTring error mentioned above, which I did not use to get with the previous version of `dependency-management-plugin` (0.6.1.RELEASE). I am able to get it working when referencing it as a project property (just `somethingVersion` without the quotes and `$`).
