### ISSUE TITLE
Allow conflict resolution to override BOM dependencies

### ISSUE THREAD

**Issue by jkschneider** [spring-gradle-plugins/dependency-management-plugin#165]
**Problem:** User (@watchwithmike) declares a dependency on `spring-boot-starter-eureka` and uses the `spring-cloud` BOM, but needs to upgrade AWS to a patch release higher than that in the BOM.

Currently, the only way they can influence the version is to use a `resolutionStrategy`, but this is brittle as it needs to be ordered before the plugin's `resolutionStrategy`.

Nebula's [dependency-recommender](https://github.com/nebula-plugins/nebula-dependency-recommender-plugin#541--conflictresolved-strategy-default) has a configuration option for conflict resolution. We could do something similar.

**Comment by wwswaziloo** [comment]
I pared down our build.gradle to cleanly show the problem:

```
buildscript {
    repositories {
        mavenCentral()
    }   
    dependencies {
        classpath 'org.springframework.boot:spring-boot-gradle-plugin:1.5.2.RELEASE'
    }   
}

apply plugin: 'spring-boot'

repositories {
    mavenCentral()
}

dependencyManagement {
    imports {
        mavenBom 'org.springframework.cloud:spring-cloud-starter-parent:Dalston.RELEASE'
    }   
}

dependencies {
    compile 'org.springframework.cloud:spring-cloud-starter-eureka'
    compile 'com.amazonaws:aws-java-sdk:1.11.119'
}
```

No matter what we do, we end up with the mavenBom "forcing" version 1.11.98 of the aws-java-sdk. In our real-world usage, we're transitively inheriting the 1.11.119 dependency from another library. You'll note that adding `{ force = true }` to the aws-java-sdk dependency makes no difference in the overwrite behavior of the mavenBom. 

I work with @watchwithmike. Let us know if we can provide any additional details. Thanks for your help @jkschneider

**Comment by wwswaziloo** [comment]
`gradle dependencyInsight --configuration compile --info --dependency aws-java-sdk` to show the (hateful) "(selected by rule)" result.

**Comment by wilkinsona** [comment]
> Currently, the only way they can influence the version is to use a resolutionStrategy, but this is brittle as it needs to be ordered before the plugin's resolutionStrategy.

As [described in the README](https://github.com/spring-gradle-plugins/dependency-management-plugin/tree/43f2c955bfd441ba3248f8cec7226ddedd11a4b3#changing-the-value-of-a-version-property), you can influence the version by overriding the `aws-java-sdk.version` property that's used by the Spring Cloud bom. For example:

```groovy
dependencyManagement {
    imports {
        mavenBom('org.springframework.cloud:spring-cloud-starter-parent:Dalston.RELEASE') {
            bomProperty 'aws-java-sdk.version', '1.11.119'
        }
    }
}
```

An added complication here is that the Spring Cloud bom's dependency management for the AWS SDK seems to be incomplete as it doesn't manage the `com.amazonaws:aws-java-sdk` dependency. You can work around that by declaring some additional dependency management for that dependency.

Putting it all together, you get a `build.gradle` that looks like this:

```groovy
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'org.springframework.boot:spring-boot-gradle-plugin:1.5.2.RELEASE'
    }
}

apply plugin: 'spring-boot'

repositories {
    mavenCentral()
}

dependencyManagement {
    imports {
        mavenBom('org.springframework.cloud:spring-cloud-starter-parent:Dalston.RELEASE') {
            bomProperty 'aws-java-sdk.version', '1.11.119'
        }
    }
    dependencies {
        dependency 'com.amazonaws:aws-java-sdk:1.11.119'
    }
}

dependencies {
    compile 'org.springframework.cloud:spring-cloud-starter-eureka'
    compile 'com.amazonaws:aws-java-sdk'
}
```

Unfortunately, due to #166, a property can't be used for the SDK version so `1.11.119` is declared in two places above. That aside, I believe the plugin already meets your needs in its current form.
