### ISSUE TITLE
"Cannot configure the 'publishing' extension after it has been accessed" when attempting to publish

### ISSUE THREAD

**Issue by nbj-nine** [spring-gradle-plugins/dependency-management-plugin#170]
I get this error from gradle when I try to publish:
'Cannot configure the 'publishing' extension after it has been accessed'

**Comment by wilkinsona** [comment]
Unfortunately, just an error message isn'tenough information to diagnose the problem with certainty. That said, I can make an educated guess.

There's a [bug in Gradle](https://github.com/gradle/gradle/issues/1373) which means that it isn't safe to access a publication's pom until a project has been evaluated. The dependency management plugin accesses the pom in order to configure it with a customisation that adds dependency management to it. If it's done too early then any Gradle configuration to Maven scope mapping customisations are lost and the resulting pom may be wrong.

To work around this problem, the dependency management plugin [now configures the pom customisation in `afterEvaluate`](https://github.com/spring-gradle-plugins/dependency-management-plugin/commit/36b05114b96b3fc41647fbc4c30b248fd62aa9c0). This change is what's triggering the failure you are seeing. I would guess it's due to the configuration of the `artifactoryPublish` task which will be "freezing" the `mainJava` publication.

You should be able to apply a similar workaround by moving your interaction with the publication into `afterEvaluate` as well. Please let us know if that works.

**Comment by nbj-nine** [comment]
Thanks @wilkinsona - we have an init.gradle that sets all this publishing up, I will try and modify that.
