### ISSUE TITLE
Versions not resolving when using JMH

### ISSUE THREAD

**Issue by corneil** [spring-gradle-plugins/dependency-management-plugin#183]
When I using this plugin on a project to handle dependency management, other plugins have problems. Like jmh gradle plugin and scala compiler.

I have modified a public project to use dependency management to illustrate the issue.
[https://github.com/corneil/compare-fp](https://github.com/corneil/compare-fp)
The dependencies branch has the modifications that cause issues.

**Comment by wilkinsona** [comment]
What problems do other plugins have? Can you provide some more details? Also, what do a need to do in the public project to recreate those problems?

**Comment by corneil** [comment]
Use the following:
Seems that any plugin trying to build a classpath has issues.
I had a look at jmh plugin code. It has project afterResolve where it adds configurations.compile to a classpath variable and same with testCompile.

```
git clone https://github.com/corneil/compare-fp.git
git checkout master
./gradlew jmh
git checkout dependencies
./gradlew jmh
```
The 2nd one should fail to start the benchmark.

**Comment by wilkinsona** [comment]
Thanks. Unfortunately, there's nothing the dependency management plugin can do about this. It doesn't work due to a design decision in the JMH plugin. It creates an [invisible, detached configuration and copies other configuration's dependencies into it](https://github.com/melix/jmh-gradle-plugin/blob/0e370ffae6188d3304c78f4eeca724385ab8f2f7/src/main/groovy/me/champeau/gradle/JMHPlugin.groovy#L270-L272):

https://github.com/melix/jmh-gradle-plugin/blob/0e370ffae6188d3304c78f4eeca724385ab8f2f7/src/main/groovy/me/champeau/gradle/JMHPlugin.groovy#L270-L272

This means that the dependency management plugin can't see the configuration (it's not part of `configurations.all`) and therefore cannot supply dependency versions when it's resolved. If you'd like this to work, you'll have to raise an enhancement request against the JMH plugin.
