### ISSUE TITLE
Exclusions support wildcard character

### ISSUE THREAD

**Issue by Aleishus** [spring-gradle-plugins/dependency-management-plugin#197]
maven dependency：
```xml
   <dependency>
                <groupId>com.ryantenney.metrics</groupId>
                <artifactId>metrics-spring</artifactId>
                <version>3.1.3</version>
                <exclusions>
                 <exclusion>
                        <artifactId>*</artifactId>
                        <groupId>org.springframework</groupId>
                    </exclusion>
                </exclusions>
            </dependency>
           
```
shall I change it like this 

```grovvy
 dependency ('com.ryantenney.metrics:metrics-spring:3.1.3'){
                    exclude 'org.springframework:*'
                }
```

**Comment by dudolino** [comment]
Is there currently a wildcard support for exclusions in the plugin like in maven 3? Would be nice to have it, but seems not to be implemented yet. I am currently having a look into the code because I would need a support for full exclusion in bom like

`
<exclusion>
<groupId>*</groupId>
<artifactId>*</artifactId>
</exclusion>
`

**Comment by wilkinsona** [comment]
@Aleishus Is that `<dependency>` within `<dependencyManagement>` in the pom?

**Comment by wilkinsona** [comment]
Closing due to the requested info not being provided.
