### ISSUE TITLE
NPE after upgrading to version 1.0.4.RELEASE

### ISSUE THREAD

**Issue by ghde** [spring-gradle-plugins/dependency-management-plugin#198]
After upgrading gradle plugin 'io.spring.dependency-management' in an existing project to version "1.0.4.RELEASE" publishing to maven repository (with gradle plugin 'maven-publish' & gradle 4.4.1) fails with the following error:

```
Caused by: java.lang.NullPointerException
        at io.spring.gradle.dependencymanagement.internal.StandardPomDependencyManagementConfigurer.configureBomImports(StandardPomDependencyManagementConfigurer.java:146)
        at io.spring.gradle.dependencymanagement.internal.StandardPomDependencyManagementConfigurer.doConfigurePom(StandardPomDependencyManagementConfigurer.java:112)
        at io.spring.gradle.dependencymanagement.internal.StandardPomDependencyManagementConfigurer.configurePom(StandardPomDependencyManagementConfigurer.java:99)
        at io.spring.gradle.dependencymanagement.internal.StandardPomDependencyManagementConfigurer.execute(StandardPomDependencyManagementConfigurer.java:93)
        at io.spring.gradle.dependencymanagement.internal.StandardPomDependencyManagementConfigurer.execute(StandardPomDependencyManagementConfigurer.java:43)
        at org.gradle.api.internal.UserCodeAction.execute(UserCodeAction.java:38)
```

Unfortunately I was not able to reproduce the issue in a vanilla project.

Any hints on how to solve the issue are very welcome.

**Comment by wilkinsona** [comment]
Looking at the code in question, one possibility is that you have imported a bom that contains a managed dependency without a version. The plugin should handle such a bom more gracefully but it would be malformed.

**Comment by ghde** [comment]
The project itself does not include a bom. It is a multi-module project and has a "dependencyManagement" > "dependencies" (within an allprojects block) to specify the versions of the project dependencies. All the dependencies there do have a version.

It somehow seems to be related to the gradle plugin of spring boot ('org.springframework.boot', Version '1.5.9.RELEASE'). I quickly locally cloned the dependency management plugin and added some log outputs to see for which dependency it is actually failing.

For line 146 the values are:
- pom: 'spring-boot-starter-parent'
- dependency: 'org.springframework:spring-context-indexer:5.0.2.RELEASE'
- other: null ('managedDependencies' map does not contain an entry for 'spring-context-indexer')

I tried to add this dependency to the 'dependencyManagement' section of my project, but no success.

**Comment by wilkinsona** [comment]
Thanks, @ghde. I think that's given me enough to figure out what's going on.

I assume that you're overriding the `spring.version` property. Boot 1.5.x uses Framework 4.3.x and you appear to be overriding it to 5.0.2.RELEASE. The `spring-context-indexer` is new in Framework 5. This is triggering a bug in the plugin during pom generation as it doesn't cope with the dependency being present in 5.0 and absent in 4.3 when trying to figure out the effect of the `spring.version` override.

This is a regression introduced by the fix for #184. The NPE can be reproduced with the following script:

```groovy
buildscript {
	repositories {
		mavenCentral()
	}
	dependencies {
		classpath 'io.spring.gradle:dependency-management-plugin:1.0.4.RELEASE'
	}
}

apply plugin: 'io.spring.dependency-management'
apply plugin: 'maven-publish'
apply plugin: 'java'

repositories {
	mavenCentral()
}

dependencyManagement {
	imports {
		mavenBom 'org.springframework.boot:spring-boot-dependencies:1.5.9.RELEASE'
	}
}

publishing {
	publications {
		mavenJava(MavenPublication) {
			from components.java
		}
	}
}

ext['spring.version'] = '5.0.2.RELEASE'
```

**Comment by ghde** [comment]
Thanks, @wilkinsona !

Yes, you are assuming right. The project overrides the spring version to '5.0.2.RELEASE'.

**Comment by mmoayyed** [comment]
I'd like to further comment on this issue: Having consulted with @wilkinsona in the Gitter chatroom, I proceeded to run a `clean` task and mistakenly thought the NPE issue had to do with stale dependencies that may have been built against Spring v5. I double checked and ensured there is no dependency overrides and tried to start fresh several times in order to remove variables. None worked. I then proceeded to put a number of DEBUG statements in the plugin and built and installed it locally to diagnose the root cause. The dependencies that were causing the NPE, per the created `id` in `StandardPomDependencyManagementConfigurer`, were related to log4j's couchbase and mongodb support none of which were being used or overridden in my own project. In all such NPEs, the `other` variable was set to null (see below):

In master in file `StandardPomDependencyManagementConfigurer` around like 146, there exists:

```java
                Dependency other = managedDependencies.get(createId(dependency));
                if (other ==  null || !dependency.getCoordinates().getVersion().equals(other.getCoordinates().getVersion())) {
                    overrides.add(dependency);
                }
```

If I look at the same section of the code in 1.0.4, I see the following:

```java
                Dependency other = managedDependencies.get(createId(dependency));
                if (!dependency.getCoordinates().getVersion().equals(other.getCoordinates().getVersion())) {
                    overrides.add(dependency);
                }
```

Notice the absence of the null check. 

In light of this, might I suggest a patch release, `1.0.4.1.RELEASE` to make the fix available? If not, for the time being I may have to revert back to Spring Boot 1.5.9. 

Thanks for your help.

**Comment by wilkinsona** [comment]
@mmoayyed Now that you understand what was causing your problem, can you please provide a small sample build script that reproduces it? I'd like to understand how widely affected people are likely to be.

**Comment by ghde** [comment]
Hi @wilkinsona 
Since I upgraded my project to spring-boot 1.5.10.RELEASE the maven publish does no longer work even tough I reverted to dependency-management version 1.0.3.RELEASE. Going back to spring-boot version 1.5.9.RELEASE the issue is resolved. To me it seems like spring-boot-gradle-plugin 1.5.10.RELEASE overrides the dependency-management plugin version which causes that version 1.0.4.RELEASE is used rather than the specified version 1.0.3.RELEASE. 

But actually I don't know if this is related to the issue of @mmoayyed and if the explanation makes any sense.

See the following sample build script to reproduce:
```
plugins {
    id 'org.springframework.boot' version '1.5.10.RELEASE'
    id 'io.spring.dependency-management' version '1.0.3.RELEASE'
}

apply plugin: 'maven-publish'
apply plugin: 'java'

repositories {
    mavenCentral()
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}

ext['spring.version'] = '5.0.2.RELEASE'
```
May I also kindly ask you to provide an updated version of the dependency-management plugin with the fix contained?

**Comment by wilkinsona** [comment]
> To me it seems like spring-boot-gradle-plugin 1.5.10.RELEASE overrides the dependency-management plugin version which causes that version 1.0.4.RELEASE is used rather than the specified version 1.0.3.RELEASE.

It's Gradle that's doing that. When there are two versions of the same dependency, Gradle will, by default, pick the latest. You can force the use of 1.0.3 with a resolution strategy:

```
buildscript {
    configurations.classpath {
        resolutionStrategy {
            force 'io.spring.gradle:dependency-management-plugin:1.0.3.RELEASE'
        }
    }
}

plugins {
    id 'org.springframework.boot' version '1.5.10.RELEASE'
}

group 'com.example'

apply plugin: 'maven-publish'
apply plugin: 'java'

repositories {
    mavenCentral()
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}

ext['spring.version'] = '5.0.2.RELEASE'
```

An updated version of the plugin will be released in due course. I'd like to understand the cause in @mmoayyed's case first. If the problem only affects people who are using Boot 1.5 and overriding `spring.version` then it's something of an edge case, particularly given the workaround noted above.

**Comment by mmoayyed** [comment]
Thank you @wilkinsona. I spent a few hours today to try to duplicate this with a vanilla Gradle build. So far, unable to do so though I do have a project here https://github.com/apereo/cas that is failing based on this issue and surely is far from a *sample* build. I'll see if I can trim it down and see why I can get the issue to manifest there, and not in a sample project generated by the initializr. One thing I have somehow managed to figure out is that the failure only occurs when the project type is set to produce a war. JAR-only-producing projects seem to not be affected by this. Mostly a working theory at this point.

More later.
