### ISSUE TITLE
Unable to pin version of dependency that is introduced by plugin

### ISSUE THREAD

**Issue by henrik242** [spring-gradle-plugins/dependency-management-plugin#200]
I am not able to force a spring-boot version of a dependency that is introduced by a plugin (gretty).

I set this:
```
dependencyManagement {
    dependencies {
        dependency "org.springframework.boot:spring-boot-starter-web:1.5.9.RELEASE"
        dependency "org.springframework.boot:spring-boot-starter:1.5.9.RELEASE"
        dependency "org.springframework.boot:spring-boot-starter-websocket:1.5.9.RELEASE"
    }
}
```
 .. but `./gradlew dependencies` still output this:
```
+--- org.springframework.boot:spring-boot-starter-websocket:1.5.4.RELEASE
|    +--- org.springframework.boot:spring-boot-starter:1.5.4.RELEASE -> 1.5.9.RELEASE (*)
|    +--- org.springframework.boot:spring-boot-starter-web:1.5.4.RELEASE (*)
```

I have a test project at  https://github.com/henrik242/gradle-dependency-pinning

**Comment by wilkinsona** [comment]
This is due to the way Gretty configures your project's dependencies. It [adds dependencies on `spring-boot-starter-websocket` and `spring-boot-starter-web` with explicitly declared versions](https://github.com/akhikhl/gretty/blob/28d24aa03e59c190dc19f97f9276754badebae03/libs/gretty/src/main/groovy/org/akhikhl/gretty/GrettyPlugin.groovy#L108-L113). These explicit versions [override the dependency management](https://github.com/spring-gradle-plugins/dependency-management-plugin#overriding-the-dependency-management) so you're seeing Gretty's version for those dependencies rather than the dependency management's version. In short, this is working as designed from the dependency management plugin's perspective.

**Comment by henrik242** [comment]
@wilkinsona Do you know of a way to override these dependencies, or is it impossible?

**Comment by wilkinsona** [comment]
You could do it in your own resolution strategy, but it'd be better if Gretty was more flexible in the version of Spring Boot that it uses.

**Comment by henrik242** [comment]
I figured it out:  Setting `ext['springBootVersion'] = "1.5.9.RELEASE"` did the trick.  Thanks for the feedback!

**Comment by wilkinsona** [comment]
And having just looked at the Gretty code, I think it already is. It'll respect a `springBootVersion` property.
