### ISSUE TITLE
How to access unresolved imported bom programmatically

### ISSUE THREAD

**Issue by jfourment** [spring-gradle-plugins/dependency-management-plugin#221]
Hi,
I'm trying to write a custom plugin to do some extra processing on _mavenBoms_ definition imported by dependency-management-plugin. Specifically, read the bom name as declared with DSL and run some queries on our local maven repos.

The public APIs only let me access a list of resolved dependencies through _managedVersion_. The list of BOM names seems to be buried deep down and not accessible by any public method.

Is there any other way to access them?

**Comment by wilkinsona** [comment]
> Is there any other way to access them?

Not at the moment. The information is [available internally](https://github.com/spring-gradle-plugins/dependency-management-plugin/blob/8621f24b52bcee6b0e9477c72667a0afaa19c3a6/src/main/java/io/spring/gradle/dependencymanagement/internal/DependencyManagement.java#L93-L95) but I'm not too keen on making it and the referenced classes public.

It's difficult to offer further guidance, or justify making the classes public, without more information about what you are trying to achieve. Perhaps you can provide your own API that delegates to this plugin's DSL?

**Comment by jfourment** [comment]
I'm trying to have a plugin to check maven repos for later versions of BOMs and show a warning. I was hoping to do something smart enough to look at what is imported in dependencyManagement to avoid duplicating bom declarations.

**Comment by wilkinsona** [comment]
Thanks for the extra details. FWIW, I would approach the problem in a different way.

There are existing Gradle plugins, such as the [Versions Plugin](https://github.com/ben-manes/gradle-versions-plugin) that will determine which dependencies have updates. The imported bom are resolved as dependencies on a `Configuration` so they could, in theory, be checked by tools like the Versions Plugin. It's only theoretical at the moment as the configurations used to resolve imported boms are detached which means they are hidden. Rather than providing an API for accessing the coordinates of the imported boms, I would rather consider using "normal" configurations that would be visible to other plugins and also to things like Gradle's `dependencies` output.

**Comment by jfourment** [comment]
I will check out this Versions plugin.  Thanks.

**Comment by wilkinsona** [comment]
I was imagining an API provided by your plugin that acts as a wrapped for this plugin. Bom imports would then be handled by your plugin, allowing it to keep track of what had been imported. It would also delegate the import to this plugin so that it could enforce the managed versions.

I've opened #226 to consider using visible configurations for resolution of imported boms. I believe this would give you what you want and is preferable to providing an API as it's more broadly beneficial.
