### ISSUE TITLE
Adding the ability to exclude configurations

### ISSUE THREAD

**Issue by nossralf** [spring-gradle-plugins/dependency-management-plugin#276]
First, thanks for a very useful plugin.

I wanted to get your opinion on adding functionality to exclude specific configurations from the dependency management plugin's versioning rules. I am aware of the ability to target only specific configurations [through configuration][1], and I agree that this should be the preferred way of configuring this plugin, but in some cases that becomes unwieldy. 

More specifically, cases with large Gradle projects with tens of sub-projects where sub-projects themselves can add various plugins which use their own configurations, where we want to enforce versioning rules globally using this plugin *except for a few select configurations*. Having to come up with, and maintain, a long list of configurations for which to use the plugin is unwieldy and brittle (adding a new configuration or plugin requires changing a global list). (Perhaps this can be done programmatically with `afterEvaluate` in some way, but I haven't been able to figure it out.)

In this case, it would be very useful with an escape hatch if a certain specific configuration needs to be excluded. The reason why I'm asking is that at work we have a case where all sub-projects depends on a specific version of `asm` (enforced with this plugin using a BOM) which is old and incompatible with JaCoCo. So we would like to exclude only the JaCoCo plugin's configurations from the versioning rules to let it pick the version of asm it requires.

The exclusion escape hatch would solve this problem neatly.

Would you be amenable to adding such an escape hatch? I'm willing to try and contribute the code for this, I just want to gauge your interest before asking permission to contribute during work hours. I would certainly prefer contributing back instead of maintaining a private fork.

Thanks for your consideration.

[1]: https://docs.spring.io/dependency-management-plugin/docs/current-SNAPSHOT/reference/html/#dependency-management-configuration-specific

**Comment by wilkinsona** [comment]
Thanks for the suggestion.

Rather than adding major new features to this plugin, our preference is that users start looking at making use of Gradle's [native support for Maven boms](https://docs.gradle.org/current/userguide/platforms.html#sub:bom_import). It takes the opposite approach with boms being applied to individual configurations (and those that extend from it) rather than globally.

It should be possible to build something that implements the behaviour that you have described on top of Gradle's platform support. Alternatively, I believe it should also be possible to build it on top of this plugin's API without forking it.
