### ISSUE TITLE
Cannot Resolve dependent bom that matches project group/name

### ISSUE THREAD

**Issue by rwinch** [spring-gradle-plugins/dependency-management-plugin#277]
[This project](https://github.com/rwinch/dependency-management-plugin-fails-project-matches-imported-bom) (highlights are below) will fail when using `./gradlew dependencies`

**build.gradle**

```
plugins {
	id "io.spring.dependency-management" version "1.0.6.RELEASE"
	id "java"
}

group = 'org.springframework'

repositories {
	mavenCentral()
}

dependencies {
	implementation "org.springframework.boot:spring-boot-starter:2.3.0.RELEASE"
}
```

**settings.gradle**
```
rootProject.name = 'spring-framework-bom'
```
**gradle.properties**
```
version=5.4.0-SNAPSHOT
```

Running the following will fail:

```
./gradlew dependencies        

> Task :dependencies FAILED

------------------------------------------------------------
Root project
------------------------------------------------------------

annotationProcessor - Annotation processors and their dependencies for source set 'main'.
No dependencies

apiElements - API elements for main. (n)
No dependencies

archives - Configuration for archive artifacts. (n)
No dependencies

compileClasspath - Compile classpath for source set 'main'.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dependencies'.
> Could not resolve all files for configuration ':detachedConfiguration29'.
   > Could not resolve org.springframework:spring-framework-bom:5.2.6.RELEASE.
     Required by:
         project :
      > Project : declares a dependency from configuration 'detachedConfiguration29' to configuration 'default' which is not declared in the descriptor for project :.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 526ms
1 actionable task: 1 executed
```

**NOTE:**

* The issue happens because the current project's group and name match the bom that is trying to be resolved
* Removing dependency management plugin fixes the dependencies task
* Version information can be found below

```
./gradlew --version

------------------------------------------------------------
Gradle 6.4.1
------------------------------------------------------------

Build time:   2020-05-15 19:43:40 UTC
Revision:     1a04183c502614b5c80e33d603074e0b4a2777c5

Kotlin:       1.3.71
Groovy:       2.5.10
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          1.8.0_242 (AdoptOpenJDK 25.242-b08)
OS:           Linux 4.15.0-99-generic amd64
```

**Context:**

This failure happens with Spring Session's Bom because it is using the NoHttpCliPlugin which has a dependency on Spring Boot. This means that Spring Session's Bom cannot resolve dependencies when using the `io.spring.dependency-management`.

**Comment by wilkinsona** [comment]
Thanks for the sample, Rob. Unfortunately, I don't think there's anything we can do about this. The problem can be reproduced without involving the dependency management plugin at all with this `build.gradle`:

```
group = 'org.springframework'

repositories {
	mavenCentral()
}

configurations {
	boms
}

dependencies {
	boms 'org.springframework:spring-framework-bom:5.2.6.RELEASE'
}

task resolvePoms {
	doFirst {
		configurations.boms.resolve()
	}
}
```

The root cause of the problem is a cycle. In this case the cycle is very short as you have a project named `org.springframework:spring-framework-bom` trying to resolve `org.springframework:spring-framework-bom`.

In Spring Session's build, the cycle is longer but it's a cycle nonetheless. IMO, `NoHttpCliPlugin` should not depend on Spring Boot. As you've seen, doing so creates a cycle if anything that Spring Boot depends upon also wants to use the `NoHttpCliPlugin`. There may be something that we can do to give Gradle a hint about how it should break the cycle, but we really shouldn't have cyclic dependencies between our projects in the first place. I've opened https://github.com/spring-io/nohttp/issues/35.

**Comment by rwinch** [comment]
This doesn't quite make sense to me. This would mean that slf4j couldn't have any configurations that include slf4j. This seems pretty limiting to me.

**Comment by wilkinsona** [comment]
It makes sense to me as I believe that circular dependencies between projects should be avoided. I'm not sure if it's possible to configure Gradle so that a circular dependency can be resolved, but even if it is possible, I don't want to add complexity to the dependency management plugin to get it to do so. I think a much better solution is to avoid the cycle in the first place.
