### ISSUE TITLE
Include overridden versions in generated POM

### ISSUE THREAD

**Issue by hban** [spring-gradle-plugins/dependency-management-plugin#28]
Versions overridden as described in "Overriding versions in a bom" are not reflected in generated POM file. This can cause problems if artifact with such POM is used as dependency.

For example:

- Project A imports Spring Platform BOM and overrides `guava.version` to 18.0
- Project B declares project A as a dependency
- Instead of Guava version 18, project B will pull version 17 (as defined in Platform BOM)

**Comment by wilkinsona** [comment]
This is tricky. When a pom _imports_ some dependency management, Maven doesn't allow the pom to override the imported pom's properties. You can only override another pom's properties if that pom is used as the parent.

Rather than only overriding `guava.version`, I think project A will need to declare its own dependency management for Guava. This should take precedence over the Spring Platform Bom that's imported. Something like this:

```groovy
dependencyManagement {
    imports {
        mavenBom 'io.spring.platform:platform-bom:1.1.1.RELEASE'
    }
    dependencies {
        'com.google.guava:guava:18.0'
    }
}
```

This will result in the following auto-generated `<dependencyManagement>` in the project's pom:

```xml
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>io.spring.platform</groupId>
            <artifactId>platform-bom</artifactId>
            <version>1.1.1.RELEASE</version>
            <scope>import</scope>
            <type>pom</type>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>18.0</version>
        </dependency>
    </dependencies>
</dependencyManagement>
```

The dependency management for Guava that's declared in the pom takes precedence over the dependency management for Guava that's imported from the Platform bom giving you the desired Guava version in this project and anything that depends upon it.

Please let me know if the above works for you and I'll make some updates to the README.

**Comment by hban** [comment]
Explicitly declared dependencies work, as expected. It's a tiny bit more work is one property is used for multiple dependencies but that is just a minor inconvenience.

 :+1: It's a good solution for this problem in my opinion.
