### ISSUE TITLE
Integrate with Gradle Version Catalogs

### ISSUE THREAD

**Issue by madorb** [spring-gradle-plugins/dependency-management-plugin#306]
This might be a long shot, as i don't know what it'd entail, but it looks like gradle 7's new version catalogs don't play nicely with this plugin - and would be awesome if it did! (or if gradle would get it together and add real support for BOM semantics directly :-) )

Import maven bom:

```
dependencyManagement {
  imports {
	// able to resolve the version from the toml file with a get
    mavenBom("org.springframework.boot:spring-boot-dependencies:${libs.versions.spring.boot.get()}")
  }
}

Declare a dependency in my `libs.versions.toml` catalog:

```
[libraries]
jackson-core = { module = "com.fasterxml.jackson.core:jackson-core" }
```

in `build.gradle.kts` declare a dependency on this version:
```
implementation(libs.jackson.core)
```

it fails with:

```
Could not find com.fasterxml.jackson.core:jackson-core:.
```

So it appears like when not specifying the version, whatever is generating the bindings from the toml is unaware of the versions provided by the mavenBom import, and thus defaults to an unknown version `.`

**Comment by madorb** [comment]
Argh, i think this was actually a problem with my multi-module configuration. Closing for the moment

**Comment by nancheung97** [comment]
Hello, I also encountered this problem. How do you integrate catalog with this plug-in?

**Comment by wilkinsona** [comment]
@nancheung97 It’s not clear what “this problem” is. It appears that @madorb’s problem was caused by a problem with his multi-module configuration.

If you believe you’ve found a problem with this plugin and you’d like someone to spend some time trying to help you, please spend some time opening a new issue and providing a complete yet minimal sample that reproduces the problem. You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to the new issue.

You may also want to investigate using Gradle’s native bom support via a platform or enforced platform rather than this plugin.

**Comment by madorb** [comment]
one rough evdge for this is that you can't seem to use the dep references created by the catalog from the `mavenBom`


e.g. one must do this:
`mavenBom("com.foo.bar:mydep-bom:${rootProject.libs.versions.foo.bom.get()}")`

vs:

`mavenBom(libs.foo.bom)`

![image](https://user-images.githubusercontent.com/823868/130118397-012e6010-e872-4c50-b29e-c02cb3dda759.png)
