### ISSUE TITLE
Fails on transitive with platform bom dependency latest.release

### ISSUE THREAD

**Issue by gabrieljones** [spring-gradle-plugins/dependency-management-plugin#382]
When a transitive dependency depends on a platform bom and uses `latest.release` as its version. The build fails with:

```log
> Could not resolve all artifacts for configuration ':app:detachedConfiguration8'.
   > Could not find com.fasterxml.jackson:jackson-bom:RELEASE.
     Searched in the following locations:
       - file:/Users/xxxx/.m2/repository/com/fasterxml/jackson/jackson-bom/RELEASE/jackson-bom-RELEASE.pom
       - https://repo.maven.apache.org/maven2/com/fasterxml/jackson/jackson-bom/RELEASE/jackson-bom-RELEASE.pom
     Required by:
         project :app
```

https://github.com/gabrieljones/spring-platform-release-failure

```
// ./transitive-platform-latest-release/build.gradle.kts
// ...
val jacksonBomVersion = "latest.release" // breaks
//val jacksonBomVersion = "[2,3[" // works

dependencies {
  implementation(platform("com.fasterxml.jackson:jackson-bom:$jacksonBomVersion"))
}
// ...
```

**Comment by gabrieljones** [comment]
We tried all manner and combination of `exclude`s, `constraint`s, `dependencyResolutionManagement` and were unable to find a workaround. Anyone else have any ideas for how to workaround this?

**Comment by wilkinsona** [comment]
Thanks for the report. The pom that Gradle generates for `transitive-platform-latest-release` appears to be the source of the problem:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <!-- This module was also published with a richer model, Gradle metadata,  -->
  <!-- which should be used instead. Do not delete the following line which  -->
  <!-- is to indicate to Gradle or any Gradle module metadata file consumer  -->
  <!-- that they should prefer consuming it instead. -->
  <!-- do_not_remove: published-with-gradle-metadata -->
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.example</groupId>
  <artifactId>transitive-platform-latest-release</artifactId>
  <version>unspecified</version>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.fasterxml.jackson</groupId>
        <artifactId>jackson-bom</artifactId>
        <version>RELEASE</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
</project>
```

Given its goal of providing a Maven-like dependency management experience, it deals with pom files and does not use Gradle module metadata. 

The dependency management plugin is trying to resolve the imported `com.fasterxml.jackson:jackson-bom:RELEASE` artifact as it needs a complete picture of the effective pom so that it can [apply Maven's exclusion semantics](https://docs.spring.io/dependency-management-plugin/docs/current/reference/html/#maven-exclusions). You can disable this feature:

```
dependencyManagement {
    applyMavenExclusions(false)
}
```

With that change in place, the reported problem no longer occurs. Unfortunately, beyond this, I don't think there's anything that can be done here and any fix would have to be made in Gradle so that it maps `latest.release` to something that's Maven-compatible when generating a pom file.
