### ISSUE TITLE
Problem when trying to use spring data fowler and spring cloud together.

### ISSUE THREAD

**Issue by leon** [spring-gradle-plugins/dependency-management-plugin#47]
Hi!

I was trying to use spring data fowler release and got that working by adding

```gradle
dependencyManagement {
    imports {
        mavenBom 'org.springframework.data:spring-data-releasetrain:Fowler-RELEASE'
    }
}
```

But in my project I also have spring cloud and as soon as I include

```gradle
compile('org.springframework.cloud:spring-cloud-starter-eureka:1.0.0.RELEASE')
```

`javax.validation` doesn't get included.

If I run the project with maven instead it works, and if I fall back to not use the fowler release it also works.

I've done a demo repo to illustrate the problem.

https://github.com/leon/temp-spring-dependency-management-plugin-problem

What could be wrong?

**Comment by checketts** [comment]
@leon Does it work if you disable maven exclusions?

````
dependencyManagement {
    applyMavenExclusions false
}
````

I ran into something similar and it seemed like the maven exclusion feature was being too insistent in its exclusions.

**Comment by leon** [comment]
That seems to fix the issue.
Though I would like to see it work without it since that is the default behavior.

It looks like spring boot is going to use this plugin under the hood for version 1.3. I hope they have it all sussed out before then :)

For reference

I was also able to get Fowler working with

```gradle
dependencyManagement {
    applyMavenExclusions false
    imports {
        mavenBom 'org.springframework.boot:spring-boot-starter-parent:1.2.3.RELEASE'
    }
}

ext['spring-data-releasetrain.version'] = 'Fowler-RELEASE'
```

Though I don't know what the best practice should be this version allows you to override other versions more easy.

**Comment by wilkinsona** [comment]
@leon Many thanks for the project that recreates the problem.

The problem still occurs with this slimmed down version of the recreation:

```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'io.spring.gradle:dependency-management-plugin:0.4.1.RELEASE'
    }
}

apply plugin: 'java'
apply plugin: 'io.spring.dependency-management'

repositories {
    jcenter()
}

dependencies {
    compile 'org.springframework.cloud:spring-cloud-starter-eureka:1.0.0.RELEASE'
    compile 'org.springframework.boot:spring-boot-starter-web:1.2.3.RELEASE'
}
```

`spring-cloud-starter-eureka` excludes `hibernate-validator` and `spring-boot-starter-web` depends on it, therefore the project should have `hibernate-validator` as a dependency and this should pull in `validation-api` as a transitive dependency.

The problem's due to the changes made in e0412c2bfc23cb3ba45c7b7d3175e8ff90de326c to tolerate cycles in the dependency graph. Rather just cutting a cycle, those changes also cut off the graph beneath any node that's already been seen. When processing `spring-boot-starter-web`, this results in `hibernate-validator`'s dependency on `validation-api` going unnoticed as it's already been seen when `spring-cloud-starter-eureka` was processed and it's excluded there.

**Comment by leon** [comment]
I'm glad you found where the problem is :)

**Comment by wilkinsona** [comment]
@leon The configuration you've [shown above](https://github.com/spring-gradle-plugins/dependency-management-plugin/issues/47#issuecomment-91251770) is what I'd recommend.
