### ISSUE TITLE
Dependency exclusions don't play nicely with `resolutionStrategy.failOnVersionConflict()`

### ISSUE THREAD

**Issue by oliverlockwood** [spring-gradle-plugins/dependency-management-plugin#61]
Consider the following `build.gradle`:
```gradle
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath "io.spring.gradle:dependency-management-plugin:0.5.3.RELEASE"
    }
}
apply plugin: "java"
apply plugin: "io.spring.dependency-management"

configurations.all {
   resolutionStrategy.failOnVersionConflict()
}
dependencyManagement {
    dependencies {
        dependency('org.mockito:mockito-core:1.9.5') {
            exclude 'org.hamcrest:hamcrest-core'
        }
        dependency('junit:junit:4.12') {
            exclude 'org.hamcrest:hamcrest-core'
        }
    }
}

dependencies {
    testCompile 'org.mockito:mockito-core'
    testCompile 'junit:junit'
}
```

If you run `./gradlew dependencies` on this, you get the following output:
```console
testCompile - Compile classpath for source set 'test'.
:dependencies FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dependencies'.
> Could not resolve all dependencies for configuration ':testCompileCopy'.
   > A conflict was found between the following modules:
      - org.hamcrest:hamcrest-core:1.1
      - org.hamcrest:hamcrest-core:1.3
```

If you comment out the `failOnVersionConflict` line and run again, you get this output:
```console
testCompile - Compile classpath for source set 'test'.
+--- org.mockito:mockito-core: -> 1.9.5
|    \--- org.objenesis:objenesis:1.0
\--- junit:junit: -> 4.12

testRuntime - Runtime classpath for source set 'test'.
[same as above]
```

This seems to suggest that the hamcrest exclusions have succeeded.  So why is the `failOnVersionConflict` firing?

Even more interestingly, if you add another dependency that transitively includes Hamcrest (e.g. `testCompile 'org.springframework.boot:spring-boot-starter-test:1.2.6.RELEASE'`) then run `./gradlew dependencies` without `failOnVersionConflict` enabled, you see this:
```console
testCompile - Compile classpath for source set 'test'.
+--- org.mockito:mockito-core: -> 1.9.5
|    +--- org.hamcrest:hamcrest-core:1.1 -> 1.3
|    \--- org.objenesis:objenesis:1.0
+--- junit:junit: -> 4.12
|    \--- org.hamcrest:hamcrest-core:1.3
\--- org.springframework.boot:spring-boot-starter-test:1.2.6.RELEASE
     +--- junit:junit:4.12 (*)
     +--- org.mockito:mockito-core:1.10.19 -> 1.9.5 (*)
     +--- org.hamcrest:hamcrest-core:1.3
     +--- org.hamcrest:hamcrest-library:1.3
     |    \--- org.hamcrest:hamcrest-core:1.3
     +--- org.springframework:spring-core:4.1.7.RELEASE
     \--- org.springframework:spring-test:4.1.7.RELEASE
          \--- org.springframework:spring-core:4.1.7.RELEASE

testRuntime - Runtime classpath for source set 'test'.
[same as above]
```
which seems to suggest that the exclusions are really not working!

I have the following questions:
1.  Do you agree that this is a bug?  If so, do you think it's a bug in this plugin or elsewhere (e.g. the `failOnVersionConflict` logic itself?
2.  Can you recommend a method I can use determine whether the exclusions are actually working and `failOnVersionConflict` is firing erroneously, or the exclusions are actually broken?  (If the former, then a workaround might be to additionally specify e.g. `dependency 'org.hamcrest:hamcrest-core:1.3'` in the `dependencyManagement`, though this is non-ideal.)

Looking forward to your thoughts, @wilkinsona!

**Comment by wilkinsona** [comment]
The exclusions look like they're working to me. You've excluded hamcrest when it's pulled in via JUnit or Mockito, but it's being pulled in as a direct dependency of Spring Boot's test starter. This is the same behaviour as you get with Maven, which is what the plugin strives to mimic. This pom:

```xml
<dependencies>
    <dependency>
        <groupId>org.mockito</groupId>
        <artifactId>mockito-core</artifactId>
        <version>1.9.5</version>
        <exclusions>
            <exclusion>
                <groupId>org.hamcrest</groupId>
                <artifactId>hamcrest-core</artifactId>
            </exclusion>
        </exclusions>
    </dependency>
    <dependency>
        <groupId>junit</groupId>
        <artifactId>junit</artifactId>
        <version>4.12</version>
        <exclusions>
            <exclusion>
                <groupId>org.hamcrest</groupId>
                <artifactId>hamcrest-core</artifactId>
            </exclusion>
        </exclusions>
    </dependency>
    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-test</artifactId>
        <version>1.2.6.RELEASE</version>
    </dependency>
</dependencies>
```

Yields this dependency tree:

```
[INFO] +- org.mockito:mockito-core:jar:1.9.5:compile
[INFO] |  \- org.objenesis:objenesis:jar:1.0:compile
[INFO] +- junit:junit:jar:4.12:compile
[INFO] \- org.springframework.boot:spring-boot-starter-test:jar:1.2.6.RELEASE:compile
[INFO]    +- org.hamcrest:hamcrest-core:jar:1.3:compile
[INFO]    +- org.hamcrest:hamcrest-library:jar:1.3:compile
[INFO]    +- org.springframework:spring-core:jar:4.1.7.RELEASE:compile
[INFO]    \- org.springframework:spring-test:jar:4.1.7.RELEASE:compile
```

The problem with `failOnVersionConflict` is trickier. As part of figuring out what the exclusions should be, the plugin takes a copy of the configuration, resolves it, analyses all of the poms that are involved, and then applies the required exclusions to the original configuration. Looking closely, you can see that the failure's occurring on `testCompileCopy` rather than `testCompile`. Unfortunately, it would appear that when a configuration is copied, its resolution strategy is also copied over. This prevents the resolution of `testCompileCopy` before it's had a chance to figure out exactly how to apply the exclusions.

In this particular case the exclusions are known ahead of time (as they're coming from dependency management that you've declared, rather than from the poms of any dependencies) so it _might_ be possible to apply them up front. I say might as I'm not 100% sure that this will be possible without subtly changing the exclusions so that they no longer match Maven's behaviour.

**Comment by wilkinsona** [comment]
No, sadly it's not possible. The only other alternative I can see is to use reflection to change the copied configuration's resolution strategy to disable fail on version conflict. However, I don't want to go down that road as it'd be very brittle due to relying on the structure of Gradle's internals.

I think you have two options:

 - Continue to use the plugin's support for exclusions and stop using `failOnVersionConflict`. If you add dependency management for `spring-boot-starter-test` with an exclusion for `hamcrest-core` you'll get the end result that you want.
 - Switch off the plugin's exclusions support (`dependencyManagement { applyMavenExclusions = false }`) and use Gradle's exclusions mechanism to get rid of `hamcrest-core`.

**Comment by wilkinsona** [comment]
Well it turns out there was a third option after all. It's possible to manually create a lighter weight copy of the original configuration that can be used to figure out the exclusions without being scuppered by `failOnVersionConflict`. A build with the fix in will be available from https://repo.spring.io/plugins-snapshot once [this build](https://build.spring.io/browse/GRADLEPLUGINS-DMP-124) has completed.

@oliverlockwood If you have a chance to try the snapshot, it'd be great to hear whether or not it's solved your problem.

**Comment by oliverlockwood** [comment]
For the record on this (with apologies for not replying sooner; I thought I had done so) the snapshot did not improve things, and neither has the latest release (version `1.0.0.RC1`).

Here is an updated `build.gradle` file which can be used to reproduce if anyone finds time to look at this issue.
```gradle
plugins {
    id "java"
    id "io.spring.dependency-management" version "1.0.0.RC1"
}

repositories {
    jcenter()
}

configurations.all {
   resolutionStrategy.failOnVersionConflict()
}
dependencyManagement {
    dependencies {
        dependency('org.mockito:mockito-core:1.9.5') {
            exclude 'org.hamcrest:hamcrest-core'
        }
        dependency('junit:junit:4.12') {
            exclude 'org.hamcrest:hamcrest-core'
        }
    }
}

dependencies {
    testCompile 'org.mockito:mockito-core'
    testCompile 'junit:junit'
    testCompile 'org.springframework.boot:spring-boot-starter-test:1.2.6.RELEASE'
}
```

**Comment by wilkinsona** [comment]
>  the snapshot did not improve things, and neither has the latest release (version 1.0.0.RC1).

As far as I can tell, 1.0.0.RC1 has improved things. The conflict is now reported when resolving `testCompile` which, crucially, is after the plugin's done its extra resolution for figuring out Maven-style exclusions.

The conflict is still reported as you haven't fully excluded hamcrest-core. There may be some room for improvement with how Maven-style exclusions are applied that could help with that. Please open a separate issue if you'd like me to dig some more.
