### ISSUE TITLE
IntelliJ IDEA inspection generates warning on dependencyManagement block

### ISSUE THREAD

**Issue by vpavic** [spring-gradle-plugins/dependency-management-plugin#63]
I did not observe any defect plugin functionality wise related to this, but thought it might be worth reporting anyway:
![intellij_gradle_warning](https://cloud.githubusercontent.com/assets/1149230/10378890/df135ed0-6e0b-11e5-9abc-7f4432011971.png)

What's interesting is that the warning disappears if ```dependencies``` closure is not the last closure within ```dependencyManagement``` block.

For example:
```groovy
dependencyManagement {
	dependencies {}
}
```
and
```groovy
dependencyManagement {
	imports {}
	dependencies {}
}
```
generate warning, but
```groovy
dependencyManagement {
	imports {}
}
```
and
```groovy
dependencyManagement {
	dependencies {}
	imports {}
}
```
do not.

This started occuring with 0.5.x releases, 0.4.x did not generate warning.

**Comment by wilkinsona** [comment]
That's a bit ugly, isn't it? Thanks for letting me know. What version of IDEA are you using?

**Comment by vpavic** [comment]
Well, it is an annoyance, but a minor one :)

I'm currently using version 14.1.5 (Ultimate edition).
When issue started occuring with 0.5.0.RELEASE I was also using some version from 14.1.x line, likely 14.1.1.

**Comment by wilkinsona** [comment]
@vpavic Unfortunately, I can't reproduce this in IntelliJ 14.1.5.

This code in `build.gradle`:

```
dependencyManagement {
    dependencies {
        dependency 'org.slf4j:slf4j-api:1.7.12'
    }
}

String foo() {
    if (true) {
        return 'boom'
    }
}
```

Warns me for `foo` but doesn't warn me for `dependencyManagement`. Can you provide more detail on how to reproduce the problem?

**Comment by vpavic** [comment]
I've moved to IDEA 15 (currently at 15.0.1) since the last comment, the warning still occurs.

Here's the complete minimal ```build.gradle``` I use to reproduce the issue:

```groovy
buildscript {
	repositories {
		jcenter()
	}

	dependencies {
		classpath 'io.spring.gradle:dependency-management-plugin:0.5.3.RELEASE'
	}
}

apply plugin: 'java'
apply plugin: 'io.spring.dependency-management'

project.sourceCompatibility = JavaVersion.VERSION_1_8

repositories {
	jcenter()
}

dependencyManagement {
	dependencies {
		dependency 'org.slf4j:slf4j-api:1.7.12'
	}
}

dependencies {
	compile 'org.slf4j:slf4j-api'
}

wrapper {
	gradleVersion = '2.9'
}
```

Sample project consist of nothing else:

```shell
vedran@vedran-ws:~/dev/projects/dependency-management-plugin-test$ tree .
.
└── build.gradle

0 directories, 1 file
```

After running ```gradle wrapper```:

```shell
vedran@vedran-ws:~/dev/projects/dependency-management-plugin-test$ tree .
.
├── build.gradle
├── gradle
│   └── wrapper
│       ├── gradle-wrapper.jar
│       └── gradle-wrapper.properties
├── gradlew
└── gradlew.bat

2 directories, 5 files
```

Steps in IDEA:
- ```File - New - Project from Existing Sources...```
- ```Import project from external model```, select Gradle, ```Next```, ```Finish``` (default import settings, ```Use default gradle wrapper```)

Opening ```build.gradle``` shows warning from screenshot in the opening comment. I've got Groovy and Gradle plugins installed.

What further info can I provide?

**Comment by wilkinsona** [comment]
Thanks, @vpavic. I've upgraded to IntelliJ 15 and I see the warning now. Interestingly, I see it with 0.4.x and 0.5.x of the plugin. That makes a certain amount of sense as the return type of `dependencies` and `imports` is `void` in both versions so I'd expect the same behaviour.

Unfortunately, as far as I can tell, this is a bug in IDEA. For reasons I don't understand it thinks that the signature of `dependencyManagement` is `Task dependencyManagement(Closure<Object> closure)`. The warning goes away when `imports {}` is last as it cannot resolve the symbol so it doesn't know if it returns `void` or not. It's unrelated, but IDEA has also incorrectly identified `dependencies` as being `Project.dependencies` and not `DependencyManagementExtension.dependencies`.

If you'd like to see the warning go away, I think you'll need to open an issue with JetBrains. If you do so, and that issue is publicly accessible, could you please link to it from this issue? Thanks.

**Comment by vpavic** [comment]
@wilkinsona, thanks for the analysis.

I've opened [IDEA-148704](https://youtrack.jetbrains.com/issue/IDEA-148704).
