### ISSUE TITLE
Original resolutionStrategy not applied when processing exclusions

### ISSUE THREAD

**Issue by eric-isakson** [spring-gradle-plugins/dependency-management-plugin#98]
In my builds I have some useVersion rules that I apply to support some custom dynamic version selection. When I combine that with this plugin, I get dependency resolution failures during io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction.findExcludedDependencies()

Here is an example build that demonstrates the issue (simplified from my actual implementation just to demonstrate this):

    buildscript {
        ext {
            springBootVersion = '1.3.5.RELEASE'
        }
        repositories {
            mavenCentral()
        }
        dependencies {
            classpath 'io.spring.gradle:dependency-management-plugin:0.+'
        }
    }

    apply plugin: 'java'
    apply plugin: 'io.spring.dependency-management'

    dependencyManagement {
        imports {
            mavenBom "org.springframework.boot:spring-boot-dependencies:${springBootVersion}"
        }
    }

    repositories {
        mavenCentral()
    }

    dependencies {
        compile 'org.apache.httpcomponents:httpclient:#4'
    }

    configurations*.resolutionStrategy {
        eachDependency { DependencyResolveDetails details ->
            if (details.requested.version.startsWith('#')) {
                details.useVersion(details.requested.version.substring(1) + '.+')
            }
        }
    }

**Comment by wilkinsona** [comment]
It's by design that original resolution strategies aren't applied to the detached configurations that are created by the plugin. See #61 for the background. You can, however, configure a resolution strategy that is applied to all the detached configurations that are created by the plugin.

Here's an updated version of your sample that shows this approach:

```groovy
buildscript {
    ext {
        springBootVersion = '1.3.5.RELEASE'
    }
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'io.spring.gradle:dependency-management-plugin:0.6.0.RELEASE'
    }
}

apply plugin: 'java'
apply plugin: 'io.spring.dependency-management'

dependencyManagement {
    imports {
        mavenBom "org.springframework.boot:spring-boot-dependencies:${springBootVersion}"
    }
}

repositories {
    mavenCentral()
}

dependencies {
    compile 'org.apache.httpcomponents:httpclient:#4'
}

Closure versionStrategy = {
    eachDependency { DependencyResolveDetails details ->
        if (details.requested.version.startsWith('#')) {
            details.useVersion(details.requested.version.substring(1) + '.+')
        }
    }
}

dependencyManagement {
    overriddenByDependencies = false
    resolutionStrategy versionStrategy
}

configurations*.resolutionStrategy versionStrategy
```

The key part is this:

```groovy
dependencyManagement {
    overriddenByDependencies = false
    resolutionStrategy versionStrategy
}
```

Without `overiddenByDependencies = false`, the `org.apache.httpcomponents:httpclient:#4` dependency results in there being dependency management for `httpclient` with a managed version of `#4`. During resolution, your resolution strategy changes it to `.+` and then the plugin's resolution strategy that applies the managed versions sets it back again. I think this could be improved without any adverse side-effects by configuring the plugin's resolution strategy first.

The ability to configure a dependency management-specific resolution strategy is [described in the README](https://github.com/spring-gradle-plugins/dependency-management-plugin#configuring-caching-of-imported-boms) but it's only mentioned as a means of configuring caching. That should probably be improved too.

**Comment by eric-isakson** [comment]
Thank you for the suggestion, I'll take a look at that.

My projects have a mixture of version specifiers. I use typical Gradle selectors for most third party libraries if they aren't managed by the BOM either with an explicit version or prefix selectors like 1.+

For our internal projects that use semantic versions, I've implemented additional version selectors like ^1.0.0 and ~1.0.0 that get converted to a combination of useVersion with some ivy range syntax to limit the possible candidates and component selection rules that reject prerelease versions depending on some other build logic. I considered forking so I could add my prefixes to Versions.DYNAMIC_PREFIXES just to work around the condition you described.

If I set overriddenByDependencies = false, my explicit selectors will still work they just won't be managed by this plugin, correct? Where this plugin would make the managed version of my first order dependency consistent accross my configurations and my transitive dependencies, I'll just fall back on the default gradle behvior of conflict resolution instead. Am I understanding that correctly?

**Comment by wilkinsona** [comment]
> Am I understanding that correctly?

You are indeed.

I think I have a fix that means that `overriddenByDependencies = false` is no longer necessary. Once [this build](https://build.spring.io/browse/GRADLEPLUGINS-DMP-165) has completed (assuming it's successful), could you please try the latest `0.6.1.BUILD-SNAPSHOT` that's available from https://repo.spring.io/plugins-snapshot?

**Comment by eric-isakson** [comment]
I have to do some additional integration to get my full resolutionStrategy applied to the dependencyManagement extension from my plugin but I did a quick hack to one of my builds and this got me past the issue that was causing my build to fail. Thanks!

**Comment by wilkinsona** [comment]
@eric-isakson Thanks for trying out the snapshot; much appreciated.

**Comment by gregallen** [comment]
similar failure here, though in my case owing to a fragmentary & invalid pom in a local repository.

Failure occurs in 0.6.0 and 0.6.1 releases. No issues in 0.5.6.

In the newer releases using exclusions to stay away from the faulty pom no longer works.

stacktrace:
```
	at io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction.findExcludedDependencies(ExclusionConfiguringAction.java:124)
	at io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction.applyMavenExclusions(ExclusionConfiguringAction.java:96)
	at io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction.execute(ExclusionConfiguringAction.java:90)
	at io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction.execute(ExclusionConfiguringAction.java:51)
```
root cause:
Caused by: org.gradle.internal.resolve.ModuleVersionResolveException
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver.resolveModule(RepositoryChainComponentMetaDataResolver.java:83)
